export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  LOGOUT_USER: "LOGOUT_USER",
  SIGN_IN_AS_GUEST: "SIGN_IN_AS_GUEST",


  GET_SELLER_PRODUCTS_REQUEST: 'GET_SELLER_PRODUCTS_REQUEST',
  GET_SELLER_PRODUCTS_SUCCESS: 'GET_SELLER_PRODUCTS_SUCCESS',
  GET_SELLER_PRODUCTS_FAILURE: 'GET_SELLER_PRODUCTS_FAILURE',
  //GET All EVENTS
  GET_ALL_ENVENTS_REQUEST: 'GET_ALL_ENVENTS_REQUEST',
  GET_ALL_ENVENTS_SUCCESS: 'GET_ALL_ENVENTS_SUCCESS',
  GET_ALL_ENVENTS_FAILURE: 'GET_ALL_ENVENTS_FAILURE',
  //GET All Hub Services
GET_ALL_HUB_SERVICES_REQUEST: 'GET_ALL_HUB_SERVICES_REQUEST',
GET_ALL_HUB_SERVICES_SUCCESS: 'GET_ALL_HUB_SERVICES_SUCCESS',
GET_ALL_HUB_SERVICES_FAILURE: 'GET_ALL_HUB_SERVICES_FAILURE',
//GET My Profile
GET_MY_PROFILE_REQUEST: 'GET_MY_PROFILE_REQUEST',
GET_MY_PROFILE_SUCCESS: 'GET_MY_PROFILE_SUCCESS',
GET_MY_PROFILE_FAILURE: 'GET_MY_PROFILE_FAILURE',
//GET My Order
GET_MY_ORDER_REQUEST: 'GET_MY_ORDER_REQUEST',
GET_MY_ORDER_SUCCESS: 'GET_MY_ORDER_SUCCESS',
GET_MY_ORDER_FAILURE: 'GET_MY_ORDER_FAILURE',
//GET MY TICKETS
GET_MY_TICKETS_REQUEST: 'GET_MY_TICKETS_REQUEST',
GET_MY_TICKETS_SUCCESS: 'GET_MY_TICKETS_SUCCESS',
GET_MY_TICKETS_FAILURE: 'GET_MY_TICKETS_FAILURE',
//GET ALL PRODUCTS
GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
//GET ALL CARDS
GET_ALL_CARDS_REQUEST: 'GET_ALL_CARDS_REQUEST',
GET_ALL_CARDS_SUCCESS: 'GET_ALL_CARDS_SUCCESS',
GET_ALL_CARDS_FAILURE: 'GET_ALL_CARDS_FAILURE',

//GET ALL CARDS
GET_ALL_EVENTS_REQUEST: 'GET_ALL_EVENTS_REQUEST',
GET_ALL_EVENTS_SUCCESS: 'GET_ALL_EVENTS_SUCCESS',
GET_ALL_EVENTS_FAILURE: 'GET_ALL_EVENTS_FAILURE',

//GET ALL CARDS
GET_ALL_SERVICES_REQUEST: 'GET_ALL_SERVICES_REQUEST',
GET_ALL_SERVICES_SUCCESS: 'GET_ALL_SERVICES_SUCCESS',
GET_ALL_SERVICES_FAILURE: 'GET_ALL_SERVICES_FAILURE',

//GET ALL CARDS
GET_MY_APPOINTMENTS_REQUEST: 'GET_MY_APPOINTMENTS_REQUEST',
GET_MY_APPOINTMENTS_SUCCESS: 'GET_MY_APPOINTMENTS_SUCCESS',
GET_MY_APPOINTMENTS_FAILURE: 'GET_MY_APPOINTMENTS_FAILURE',

//GET ALL CARDS
GET_CART_LIST_REQUEST: 'GET_CART_LIST_REQUEST',
GET_CART_LIST_SUCCESS: 'GET_CART_LIST_SUCCESS',
GET_CART_LIST_FAILURE: 'GET_CART_LIST_FAILURE',
};
